{
 "title": "Sonic-Exporter Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "target",
    "label": "Switch",
    "query": {
     "query": "label_values(sonic_device_info{job=\"$sonic_expo\"}, instance)"
    }
   },
   {
    "name": "sonic_expo",
    "query": {
     "query": "label_values(sonic_device_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Device Type",
   "type": "table",
   "targets": [
    {
     "expr": "sonic_device_info{instance=\"$target\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "options": {
    "content": "* Select the switch from the dropdown above.\n* For simulated GNS3 switches platform data like PDUs, FANs etc. will not be available for obvious reasons.\n* Graph may show \"No Data\" for the metrics which don't have respective configuration on the switch.\n* As an internal mgmt. in our lab, outside of working hours Real Physical Switches are powered down, Hence monsoon shows no data for that duration. "
   }
  },
  {
   "title": "Sonic System Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "aggregation": "Last",
     "alias": "dfdxcvbcx",
     "crit": "2",
     "decimals": 2,
     "displayAliasType": "Always",
     "displayType": "Annotation",
     "displayValueWithAlias": "When Alias Displayed",
     "expr": "sonic_system_status{instance=\"$target\",status=\"\",status_core=\"\"}",
     "group": { "$$hashKey": "object:24", "alias": "", "name": "Status Checks", "url": "" },
     "legendFormat": "{{instance}}",
     "units": "none",
     "url": "xcvbxcvb",
     "valueDisplayRegex": "xcvb",
     "valueHandler": "String Threshold",
     "warn": "1"
    }
   ]
  },
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device Info",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sonic_device_info{instance=\"$target\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Device Up Time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "sonic_device_uptime_seconds_total{instance=\"$target\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonic_device_memory_ratio{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "FAN's Availability Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sonic_device_fan_available_status{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 7, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonic_device_cpu_ratio{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "FAN RPM",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonic_device_fan_rpm{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "FAN Operational Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "sonic_device_fan_operational_status{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "Sensors Tempt. Threshold",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonic_device_sensor_threshold_celsius{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "Sensor's Tempt.",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonic_device_sensor_celsius{instance=\"$target\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "MCLAG",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "MCLAG State Info",
     "type": "table",
     "gridPos": { "h": 4, "w": 16, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sonic_mclag_oper_state{instance=\"$target\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Mclag Domain Operational Status",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 5, "x": 16, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sonic_mclag_oper_state{instance=\"$target\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "MCLAG Domain Info",
     "type": "table",
     "gridPos": { "h": 4, "w": 16, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sonic_mclag_domain{instance=\"$target\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Time Protocol (NTP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "NTP Sync Status",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonic_ntp_sync_status{instance=\"$target\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "NTP Jitter- Mean deviation in times between the switch and the NTP server.",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 3, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sonic_ntp_jitter{instance=\"$target\"}",
       "legendFormat": "[remote={{remote}}, refid={{refid}}]"
      }
     ]
    },
    {
     "title": "Round-trip delay to the NTP server.",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sonic_ntp_rtd{instance=\"$target\"}",
       "legendFormat": "[remote-{{remote}}, refid-{{refid}}]"
      }
     ]
    },
    {
     "title": "NTP Global",
     "type": "table",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sonic_ntp_global{instance=\"$target\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "NTP Offset- Time difference between the switch and the NTP server",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 3, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sonic_ntp_offset{instance=\"$target\"}",
       "legendFormat": "[remote-{{remote}}, refid-{{refid}}]"
      }
     ]
    },
    {
     "title": "Time since last synchronized.",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sonic_ntp_when{instance=\"$target\"}",
       "legendFormat": "[remote-{{remote}}, refid-{{refid}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Digital Optical Monitoring (DOM)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tranceiver Info",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sonic_interface_transceiver_info{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "Interface Cable Info",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sonic_interface_cable_length_meters{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "DOM Optic Threshold Info. (power=dBm, vcc=volts, tempt.= °C, bias= mA)",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sonic_transceiver_threshold_info{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "DOM Optic Voltage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "sonic_interface_optic_volts{instance=\"$target\"}",
       "legendFormat": "{{port}} {{interface}}"
      }
     ]
    },
    {
     "title": "DOM Optic Tempt.",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "sonic_interface_optic_celsius{instance=\"$target\"}",
       "legendFormat": "{{port}} {{interface}}"
      }
     ]
    },
    {
     "title": "DOM Bias Ampere",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "mamp" } },
     "targets": [
      {
       "expr": "sonic_interface_transmit_optic_bias_amperes{instance=\"$target\"}",
       "legendFormat": "{{port}} {{interface}}"
      }
     ]
    },
    {
     "title": "DOM Optic Rx Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "sonic_interface_receive_optic_power_dbm{instance=\"$target\"}",
       "legendFormat": "{{port}} {{interface}}"
      }
     ]
    },
    {
     "title": "DOM Optic Tx Power",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "sonic_interface_transmit_optic_power_dbm{instance=\"$target\"}",
       "legendFormat": "{{port}} {{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Critical Resource Monitoring (CRM)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CRM STATS",
     "type": "table",
     "gridPos": { "h": 17, "w": 16, "x": 0, "y": 109 },
     "targets": [
      {
       "expr": "crm_acl_stats_egress_lag_crm_stats_acl_group_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_egress_lag_crm_stats_acl_table_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_egress_port_crm_stats_acl_group_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_egress_port_crm_stats_acl_table_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_egress_rif_crm_stats_acl_group_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_egress_rif_crm_stats_acl_table_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_egress_switch_crm_stats_acl_group_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_egress_switch_crm_stats_acl_table_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_egress_vlan_crm_stats_acl_group_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_egress_vlan_crm_stats_acl_table_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_ingress_lag_crm_stats_acl_group_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_ingress_lag_crm_stats_acl_table_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_ingress_port_crm_stats_acl_group_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_ingress_port_crm_stats_acl_table_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_ingress_rif_crm_stats_acl_group_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_ingress_rif_crm_stats_acl_table_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_ingress_switch_crm_stats_acl_group_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_ingress_switch_crm_stats_acl_table_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_ingress_vlan_crm_stats_acl_group_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_acl_stats_ingress_vlan_crm_stats_acl_table_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_stats_dnat_entry_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_stats_fdb_entry_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_stats_ipmc_entry_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_stats_ipv4_neighbor_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_stats_ipv4_nexthop_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_stats_ipv4_route_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_stats_ipv6_neighbor_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_stats_ipv6_nexthop_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_stats_ipv6_route_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_stats_nexthop_group_member_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_stats_nexthop_group_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      },
      {
       "expr": "crm_stats_snat_entry_used{instance=\"$target\"}",
       "legendFormat": "{{__name__}} , Total available={{available}}"
      }
     ]
    }
   ]
  },
  { "title": "Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Packets received on Ethernet in every $__interval range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "increase(sonic_interface_received_ethernet_packets_total{instance=\"$target\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Interface Operational Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sonic_interface_operational_status{instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "Interface queued packets in every $__interval range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "increase(sonic_interface_queue_processed_packets_total{instance=\"$target\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Interface queued bytes in every $__interval range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "increase(sonic_interface_queue_processed_bytes_total{instance=\"$target\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Interface Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sonic_interface_info{instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "Interface Tx Bytes in every $__interval range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "increase(sonic_interface_transmitted_bytes_total{instance=\"$target\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Interface Rx Bytes in every $__interval range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "increase(sonic_interface_received_bytes_total{instance=\"$target\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Interface Rx error packet in every $__interval range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "increase(sonic_interface_receive_error_input_packets_total{instance=\"$target\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Interface Rx Packets in every $__interval range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "increase(sonic_interface_received_packets_total{instance=\"$target\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Interface Tx Packets in every $__interval range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "increase(sonic_interface_transmitted_packets_total{instance=\"$target\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Interface Tx error packet count in every $__interval range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "increase(sonic_interface_transmit_error_output_packets_total{instance=\"$target\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Size of the Ethernet Frames transmitted in every $__interval range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "increase(sonic_interface_transmitted_ethernet_packets_total{instance=\"$target\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Interface admin status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sonic_interface_admin_status{instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "Unix Time since last flap of interface ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "sonic_interface_last_flapped_seconds_total{instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "PSU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "PSU Operational Status",
     "type": "table",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sonic_device_psu_operational_status{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "PSU Availability",
     "type": "table",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 21 },
     "targets": [
      {
       "expr": "sonic_device_psu_available_status{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "PSU Info",
     "type": "table",
     "gridPos": { "h": 5, "w": 16, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sonic_device_psu_info{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "PSU Input Current",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonic_device_psu_input_amperes{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "PSU Input Volts",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonic_device_psu_input_volts{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "PSU Tempt.",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sonic_device_psu_celsius{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "PSU Output Current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 17, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "sonic_device_psu_output_amperes{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "PSU Output Voltage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "volts" } },
     "targets": [
      {
       "expr": "sonic_device_psu_output_volts{instance=\"$target\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Static Anycast Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "SAG Info",
     "type": "table",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sonic_sag_info{instance=\"$target\"}"
      }
     ]
    },
    {
     "title": "SAG Admin Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 6, "y": 22 },
     "targets": [
      {
       "expr": "sonic_sag_admin_status{instance=\"$target\"}",
       "legendFormat": "gw_ip={{gateway_ip}} intfc={{interface}} ip_fmly={{ip_family}} vni={{vni}}"
      }
     ]
    },
    {
     "title": "SAG Operational Status",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
     "targets": [
      { "expr": "sonic_sag_operational_status" }
     ]
    }
   ]
  },
  {
   "title": "BGP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "BGP Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "expr": "sonic_bgp_status{instance=\"$target\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "BGP IPV4 Peer Uptime",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sonic_bgp_uptime_seconds_total{instance=\"$target\", message_type=\"ipv4\"}",
       "legendFormat": "Peer_AS={{remote_as}} Peer={{peer_name}} MsgType={{message_type}}"
      }
     ]
    },
    {
     "title": "BGP EVPN Peer Uptime",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 9, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sonic_bgp_uptime_seconds_total{instance=\"$target\", message_type=\"evpn\"}",
       "legendFormat": "Peer_AS={{remote_as}} Peer={{peer_name}} MsgType={{message_type}}"
      }
     ]
    },
    {
     "title": "IPV4 BGP Messages Tx from Peers in every $__interval range",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "increase(sonic_bgp_messages_transmitted_total{instance=\"$target\", message_type=\"ipv4\"}[$__interval])",
       "legendFormat": "Peer_AS={{remote_as}} Peer={{peer_name}} MsgType={{message_type}}"
      }
     ]
    },
    {
     "title": "EVPN BGP Messages Tx from Peers in every $__interval range",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 9, "y": 35 },
     "targets": [
      {
       "expr": "increase(sonic_bgp_messages_transmitted_total{instance=\"$target\", message_type=\"evpn\"}[$__interval])",
       "legendFormat": "Peer_AS={{remote_as}} Peer={{peer_name}} MsgType={{message_type}}"
      }
     ]
    },
    {
     "title": "BGP IPV4 Messages Rx by Peers in every $__interval range",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "increase(sonic_bgp_messages_received_total{instance=\"$target\", message_type=\"ipv4\"}[$__interval])",
       "legendFormat": "Peer_AS{{remote_as}} Peer={{peer_name}} MsgType={{message_type}}"
      }
     ]
    },
    {
     "title": "BGP EVPN Messages Rx by Peers in every $__interval range",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 9, "y": 41 },
     "targets": [
      {
       "expr": "increase(sonic_bgp_messages_received_total{instance=\"$target\", message_type=\"evpn\"}[$__interval])",
       "legendFormat": "Peer_AS{{remote_as}} Peer={{peer_name}} MsgType={{message_type}}"
      }
     ]
    },
    {
     "title": "Total BGP IPV4 Prefixes Tx from Peers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sonic_bgp_prefixes_transmitted_total{instance=\"$target\", message_type=\"ipv4\"}",
       "legendFormat": "Peer_AS={{remote_as}} Peer={{peer_name}} MsgType={{message_type}}"
      }
     ]
    },
    {
     "title": "Total BGP EVPN Prefixes Tx from Peers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 9, "y": 47 },
     "targets": [
      {
       "expr": "sonic_bgp_prefixes_transmitted_total{instance=\"$target\", message_type=\"evpn\"}",
       "legendFormat": "Peer_AS={{remote_as}} Peer={{peer_name}} MsgType={{message_type}}"
      }
     ]
    },
    {
     "title": "Total BGP IPV4 Prefixes Rx by Peers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "sonic_bgp_prefixes_received_total{instance=\"$target\", message_type=\"ipv4\"}",
       "legendFormat": "Peer_AS={{remote_as}} Peer={{peer_name}} MsgType={{message_type}}"
      }
     ]
    },
    {
     "title": "Total BGP EVPN Prefixes Rx by Peers",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 9, "y": 53 },
     "targets": [
      {
       "expr": "sonic_bgp_prefixes_received_total{instance=\"$target\", message_type=\"evpn\"}",
       "legendFormat": "Peer_AS={{remote_as}} Peer={{peer_name}} MsgType={{message_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "EVPN",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status of the EVPN Endpoints",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sonic_evpn_status{instance=\"$target\"}",
       "legendFormat": "intfc={{interface}} osi_layer={{osi_layer}}"
      }
     ]
    },
    {
     "title": "VXLAN Operational Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 9, "y": 24 },
     "targets": [
      {
       "expr": "sonic_vxlan_operational_status{instance=\"$target\"}",
       "legendFormat": "neighbor={{neighbor}}"
      }
     ]
    },
    {
     "title": "Number of remote VTEPs associated with VNI",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sonic_evpn_remote_vteps{instance=\"$target\"}",
       "legendFormat": "intfc={{interface}} osi_layer={{osi_layer}} vni={{vni}} vrf={{vrf}}"
      }
     ]
    },
    {
     "title": "Number of ARPs cached for the VNI",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 9, "y": 30 },
     "targets": [
      {
       "expr": "sonic_evpn_arps{instance=\"$target\"}",
       "legendFormat": "intfc={{interface}} osi_layer={{osi_layer}} vni={{vni}} vrf={{vrf}}"
      }
     ]
    },
    {
     "title": "Number of L2 vnis associated with an L3 VNI",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sonic_evpn_l2_vnis{instance=\"$target\"}",
       "legendFormat": "intfc={{interface}} osi_layer={{osi_layer}} svi={{svi}} vni={{vni}} vrf={{vrf}}"
      }
     ]
    },
    {
     "title": "Number of Mac Addresses learned VNI",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 9, "y": 35 },
     "targets": [
      {
       "expr": "sonic_evpn_mac_addresses{instance=\"$target\"}",
       "legendFormat": "intfc={{interface}} osi_layer={{osi_layer}} vni={{vni}} vrf={{vrf}}"
      }
     ]
    }
   ]
  }
 ]
}