COUNTER_PORT_MAP = "COUNTERS_PORT_NAME_MAP"
COUNTER_QUEUE_MAP = "COUNTERS_QUEUE_NAME_MAP"
COUNTER_QUEUE_TYPE_MAP = "COUNTERS_QUEUE_TYPE_MAP"
COUNTER_TABLE_PREFIX = "COUNTERS:"
COUNTER_IGNORE = ["cpu"]
COUNTER_ETHER_MTU_SIZES = zip(
    (64, 127, 255, 511, 1023, 1518, 2047, 4095, 9216, 16383),
    [
        "SAI_PORT_STAT_ETHER_IN_PKTS_64_OCTETS",
        "SAI_PORT_STAT_ETHER_IN_PKTS_65_TO_127_OCTETS",
        "SAI_PORT_STAT_ETHER_IN_PKTS_128_TO_255_OCTETS",
        "SAI_PORT_STAT_ETHER_IN_PKTS_256_TO_511_OCTETS",
        "SAI_PORT_STAT_ETHER_IN_PKTS_512_TO_1023_OCTETS",
        "SAI_PORT_STAT_ETHER_IN_PKTS_1024_TO_1518_OCTETS",
        "SAI_PORT_STAT_ETHER_IN_PKTS_1519_TO_2047_OCTETS",
        "SAI_PORT_STAT_ETHER_IN_PKTS_2048_TO_4095_OCTETS",
        "SAI_PORT_STAT_ETHER_IN_PKTS_4096_TO_9216_OCTETS",
        "SAI_PORT_STAT_ETHER_IN_PKTS_9217_TO_16383_OCTETS",
    ],
)
TRANSCEIVER_DOM_SENSOR = "TRANSCEIVER_DOM_SENSOR|"
TRANSCEIVER_DOM_SENSOR_PATTERN = f"{TRANSCEIVER_DOM_SENSOR}*"
TRANSCEIVER_INFO = "TRANSCEIVER_INFO|"
TRANSCEIVER_INFO_PATTERN = f"{TRANSCEIVER_INFO}Ethernet*"
TRUE_VALUES = ["up", "true", "Ready", "ready"]

PSU_INFO = "PSU_INFO|"
PSU_INFO_PATTERN = f"{PSU_INFO}|PSU*"